### ISSUE TITLE
Colors doesn't apply to URIs

### ISSUE THREAD

**Issue by stasbar** [fusesource/jansi#101]
Hello.
I'm facing with problem, that the color is not applied to URIs 
code:
![Image1](https://i.imgur.com/q6WQ3bW.png)
output:
![Image2](https://i.imgur.com/xEhm4lp.png)

**Comment by gnodet** [comment]
Jansi does not do anything related to URL, so I don't think the problem comes from Jansi.
Please reopen after testing with 2.0.x if needed.
