### ISSUE TITLE
Does not work with Eclipse 'ANSI Escape in Console' plugin

### ISSUE THREAD

**Issue by JesseVelden** [fusesource/jansi#102]
When I am using the `ANSI Escape in Console` Eclipse plugin and doing `AnsiConsole.systemInstall();`, it doesn't output any color codes in the Eclipse console.   
Without `AnsiConsole.systemInstall();` ANSI Escape characters are parsing fine with the plugin.

**Comment by hboutemy** [comment]
like #87, how can we detect that the console supports ANSI escape codes? is there any system property?

**Comment by tnekohue** [comment]
```java
public static boolean isEclipse() {
    boolean isEclipse = System.getProperty("java.class.path").toLowerCase().contains("eclipse");
    return isEclipse;
}
if(!isEclipse()){
   AnsiConsole.systemInstall();
}
```
This effectivly detects eclipse.
Unfortunatly, there is never one way to tell if something supports escape codes.

**Comment by gnodet** [comment]
> like #87, how can we detect that the console supports ANSI escape codes? is there any system property?

You can use `-Djansi.force=true` system property.  This causes other problems with Eclipse, as it expects all ansi sequences to be supported, which is definitely not the case in the eclipse console unfortunately.

Unfortunately, I also can't see any environment variable or system property that could be used to automatically detect the Eclipse environment...
