### ISSUE TITLE
An OutputStream/Writer that doesn't print ANSI codes that are already set

### ISSUE THREAD

**Issue by cjohnstoniv** [fusesource/jansi#105]
If an ANSI style is already set (i.e. the stream/writer knows it was the last ANSI style it set), is there any way to have a writer that automatically strips out a repeat of the same style if it is sent before a reset or different overriding style?

**Comment by hboutemy** [comment]
currently, the state is not kept

**Comment by gnodet** [comment]
@cjohnstoniv you could have a look at JLine's [`AttributedString`](https://github.com/jline/jline3/blob/master/terminal/src/main/java/org/jline/utils/AttributedString.java) which can remove duplicate ansi sequences if needed (though not as a stream).
