### ISSUE TITLE
Need 1.17.1 release

### ISSUE THREAD

**Issue by dantran** [fusesource/jansi#114]
The current latest has a fix for maven 3.5.3 windows jansi issue

https://mail-archives.apache.org/mod_mbox/maven-dev/201803.mbox/browser

**Comment by famod** [comment]
Do you mean the fix for #110?
If yes: I created a corresponding ticket for Maven, see https://issues.apache.org/jira/browse/MNG-6382.

**Comment by hboutemy** [comment]
I just updated Jira issues to better document the 2 issues that hit Maven: at Jansi level, it's #107 and #110
At Maven level, corresponding issues are https://issues.apache.org/jira/browse/MNG-6372 and https://issues.apache.org/jira/browse/MNG-6382

**Comment by stephenc** [comment]
Any progress? I'd like to roll Maven 3.5.4 with these fixes when they are ready

**Comment by gnodet** [comment]
Done weeks ago...  https://repo1.maven.org/maven2/org/fusesource/jansi/jansi/1.17.1/

**Comment by hboutemy** [comment]
oh, sorry, didn't check
I'll add a link in the README...

thank you

**Comment by gnodet** [comment]
Opps, sorry.  I had to cherry-pick your changes and force push.
