### ISSUE TITLE
JAnsi isn't uninstalled if sdterr is redirected

### ISSUE THREAD

**Issue by klenium** [fusesource/jansi#125]
From https://github.com/fusesource/jansi/issues/124

If stdout is redirected, then everything that's printed using JAnsi after calling AnsiConsole.systemUninstall will have colors! If stdout isn't redirected, I see random caracters after the uninstall, just as how it should work. See the image.

![custom-test](https://user-images.githubusercontent.com/4959489/39093700-ec34ea5a-4623-11e8-8e51-97c9cc95d438.PNG)

Test program:

    public static void main(String[] args) {
        AnsiConsole.systemInstall();
        print(System.out, "Lorem ipsum");
        print(System.err, "dolor sit amet");
        AnsiConsole.systemUninstall();
        print(System.out, "consectetur adipiscing elit");
        print(System.err, "Donec lectus lectus");
    }
    private static void print(PrintStream stream, String text) {
        int half = text.length() / 2;
        stream.print(text.substring(0, half));
        stream.println(Ansi.ansi().fg(Ansi.Color.GREEN).a(text.substring(half)).reset());
    }

**Comment by hboutemy** [comment]
thanks for the new issue: this makes it clear and helps digging in depth

I tried to dump the PrintStream class name to check if System.err was back to the normal PrintStream: `stream.print(stream.getClass().getName() + "  " + text.substring(0, half));`

result: the color is displayed even if the normal PrintStream is used
I'm puzzled...

**Comment by hboutemy** [comment]
next try: I tested with AnsiConsole.system_err, which should never be able to display color: it displays color, before or after systemUninstall()...

**Comment by gnodet** [comment]
One thing that happens is that the console mode may be changed to support `ENABLE_VIRTUAL_TERMINAL_PROCESSING` but this change is not reverted.

**Comment by gnodet** [comment]
Fixed by https://github.com/fusesource/jansi/commit/63bd892b2bdfc253ec119a57bdd42df5e80fd859
