### ISSUE TITLE
Using Jansi throughout project

### ISSUE THREAD

**Issue by auroraite** [fusesource/jansi#127]
Hello I would like to use Jansi with Log4j2. My question is if I do the static call to install once and don't un-install it, would it run the ANSI format throughout my programs runtime? Basically for all my logs I want it do display a color.

Would keeping it installed be safe?

Thanks.

**Comment by tnekohue** [comment]
AnsiConsole.systemInstall(); without a corresponding uninstall will result in remaining active until program exit.
It replaces the System.out and System.err streams with its own.
It is perfectly safe to call this method multiple times as it keeps track, and only uninstalls when the AnsiConsole.systemUninstall(); method has been called the same number of times.

**Comment by gnodet** [comment]
Yes, there's no problem in not uninstalling the streams.
