### ISSUE TITLE
"package does not exist" error

### ISSUE THREAD

**Issue by arsari** [fusesource/jansi#129]
Hi,

1. I download `jansi-1.17.1.jar` and extract the content.
2. I copied the org directory to my java file directory.
3. I add the statement `import org.fusesource.jansi.AnsiConsole;` in my java file but I get the message in NetBeans `package org.fusesource.jansi.AnsiConsole does not exist`. 
4. I open my cmd prompt and write `java -cp . org.fusesource.jansi.AnsiConsole` and get the error message that AnsiConsole class do not have a main method.

~~~txt
C:\Users\asantiago\OneDrive\Coding_Work\Java-Practice>java -cp . org.fusesource.jansi.AnsiConsole
Error: Could not find or load main class org.fusesource.jansi.AnsiConsole
~~~

How can I import the package for use in my program?

**Comment by khmarbaise** [comment]
Are you using things like Maven ? It does not look like that...

**Comment by gnodet** [comment]
Try using
```
> java -jar jansi/target/jansi-1.17.1.jar 
```
