### ISSUE TITLE
Automatic-Module-Name in JAR's Manifest-File

### ISSUE THREAD

**Issue by refcodes** [fusesource/jansi#130]
It would help other Java 9 modules and their `module-info.java` declaration to put an entry into jansi's JAR Manifest-File, such as: `Automatic-Module-Name: org.fusesource.jansi` to get stable module references. In Maven, this can be achieved by tweaking the `maven-jar-plugin` similar to:
```
<plugin>
	<groupId>org.apache.maven.plugins</groupId>
	<artifactId>maven-jar-plugin</artifactId>
	<configuration>
		<archive>
			...
			<manifestEntries>
				<Automatic-Module-Name>org.fusesource.jansi</Automatic-Module-Name>
			</manifestEntries>
		</archive>
	</configuration>
	...
</plugin>
```
Then other JARs using jansi can move on to Java 9's module system :-)

**Comment by hboutemy** [comment]
good idea, done
did also for HawtJNI Runtime: will be released in 1.17
there is also jansi-native and jansi-${platform}: will be in 1.9

**Comment by metacodez** [comment]
Hi there, I love jansi! When will version 1.9 be availabe? I switched my artifacts to be modules ("org.refcodes" group) as of Java 9 and now maven complains about jansi 1.8 ("Required filename-based automodules detected. Please don't publish this project to a public artifact repository!). Thanks a lot beforehhand!

**Comment by metacodez** [comment]
Hi there, me again :-) Regarding Java >= 9 modularity, is it planned to give jansi a `module-info.java` file? This would help to build a down stripped runtime image with only the required java modules (e.g.  `mvn jlink:jlink` for applications using jansi). There are tools like `moditect` which can help getting around the required `module-info.class` file, but having a `module-info.class` defined by the jansi library itself would make live easier :-) Should I open a separate issue for this proposal or is it out of scope?
