### ISSUE TITLE
jansi-project?

### ISSUE THREAD

**Issue by peterremote1980** [fusesource/jansi#138]
what is the different between these two projects
<artifactId>jansi</artifactId> 
<artifactId>jansi-project</artifactId>

thanks

**Comment by hboutemy** [comment]
jansi-project could have been named "jans-root" or "jansi-parent" or "jansi-reactor", whatever naming makes you more clear about its pure internal nature to aggregate a few parts during Maven build

jansi is *the* artifact that everybody will consume, it's one of the modules that jansi-project agggregates at build

**Comment by peterremote1980** [comment]
thanks a lot
