### ISSUE TITLE
Version 1.18 listed on maven but not github or on main site

### ISSUE THREAD

**Issue by skyghis** [fusesource/jansi#139]
Maven central list a [version 1.18](https://search.maven.org/artifact/org.fusesource.jansi/jansi/1.18/jar) but I can't find any information about this release on [github](https://github.com/fusesource/jansi/releases) or on [main web site](http://fusesource.github.io/jansi/).

Should I use version 1.18 ? if yes, what are the changes ?

Thanks

**Comment by hboutemy** [comment]
just fixed
