### ISSUE TITLE
mutlithreading issue, missing synchronized in toplevel FilterPrintStream  write(String), write(byte[] buf, int off, int len), write(char[])

### ISSUE THREAD

**Issue by Arnaud-Nauwynck** [fusesource/jansi#142]
when using several threads that print long strings, then printed lines may be incorrectly mixed.

There is a missing synchronized in 3 toplevel FilterPrintStream methods:
- write(byte[] buf, int off, int len)
- write(char[])
- write(String)    ... calling write(char[])

However, performance are poor because there is an extra synchronized for each char printed in lower-level protected method AnsiPrintStream 
- protected synchronized boolean filter(int data)

**Comment by gnodet** [comment]
This has been fixed in 2.x.
