### ISSUE TITLE
Outdated "maven-metadata.xml" on Maven Central

### ISSUE THREAD

**Issue by alexisjehan** [fusesource/jansi#159]
https://repo1.maven.org/maven2/org/fusesource/jansi/jansi/maven-metadata.xml

That is annoying because it tells that the last release is the 1.11 one instead of the 1.18 one.
I guess that it will be fixed with the next deployment.

The issue itself may be from Maven side and not Jansi directly.

**Comment by khmarbaise** [comment]
Created an issue for the Central support https://issues.sonatype.org/browse/MVNCENTRAL-5264

**Comment by hboutemy** [comment]
@khmarbaise it seems MVNCENTRAL-5264 has not been fixed (private issue, can't look content)
can you check, please?

**Comment by khmarbaise** [comment]
The JIRA ticket has been closed and marked solved but if I check the maven-metadata.xml it looks wrong ...furthermore the `maven-metadata.xml` file has a modified date of 2013 whereas other files are of 2017 ... ?

**Comment by alexisjehan** [comment]
It may be fixed with the next release so...

**Comment by alexisjehan** [comment]
Fixed with new releases.
