### ISSUE TITLE
bgBrightCyan changes Foreground colour

### ISSUE THREAD

**Issue by markjfisher** [fusesource/jansi#163]
Ansi.java line 483:

    public Ansi bgBrightCyan() {
        return this.fgBright(Color.CYAN);
    }

**Comment by markjfisher** [comment]
I've also noticed the normal bgCyan is wrong too

    public Ansi bgCyan() {
        return this.fg(Color.CYAN);
    }

**Comment by hboutemy** [comment]
good finding, fixed
thank you
