### ISSUE TITLE
ANSI Output no longer working on Eclipse version 2019-12.

### ISSUE THREAD

**Issue by scottie-uk** [fusesource/jansi#169]
I am using Eclipse 2019-12 (4.14.0) and I attempting to install and use your project from the Eclipse market place. However, when I do the command line output does not support ANSI colors.  I have had it working on other versions of Eclipse and did set it up on my office PC (Windows).

I tried also installing it from the Install New Software feature of Eclipse but it does not complete, Eclipse complains about not finding some repository or other. See below:
```

An error occurred while collecting items to be installed
session context was:(profile=C__Program Files_eclipse-java-2019-122_eclipse, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
No repository found containing: osgi.bundle,org.eclipse.emf.common,2.18.0.v20191225-1014
No repository found containing: osgi.bundle,org.eclipse.emf.ecore,2.21.0.v20200127-1342
No repository found containing: osgi.bundle,org.slf4j.api,1.7.30.v20200204-2150
No repository found containing: org.eclipse.update.feature,org.eclipse.emf.common,2.18.0.v20191225-1014
No repository found containing: org.eclipse.update.feature,org.eclipse.emf.ecore,2.21.0.v20200127-1342

```
Are there current issues with Eclipse 2019-12 or do I have to do something to enable ANSI support once the plug in is installed?

**Comment by gnodet** [comment]
Not sure, but the bundles are not related to jansi, so not sure if that's really related to jansi.
