### ISSUE TITLE
Colors are not interpreted anymore on Windows 10 cmd/PowerShell with the new 2.1.0 release

### ISSUE THREAD

**Issue by alexisjehan** [fusesource/jansi#182]
```java
package foo;

import org.fusesource.jansi.Ansi;
import org.fusesource.jansi.AnsiConsole;

import java.io.PrintStream;

public class Foo {

	public static void main(final String[] args) {
		final PrintStream output = AnsiConsole.out();
		output.println(Ansi.ansi().fgBrightRed().a("Hello world").reset());
	}
}
```

Was working until 2.0.1:
![2 0 1](https://user-images.githubusercontent.com/9216831/101495918-6859d880-3969-11eb-9434-64568b96ab45.png)

Does not work anymore since 2.1.0:
![2 1 0](https://user-images.githubusercontent.com/9216831/101495929-6a239c00-3969-11eb-9c0d-b9143dd499b2.png)

Thanks in advance having a look.

**Comment by gnodet** [comment]
I've just tried both cmd and PowerShell on Windows 10 and it works for me.  Do you have the latest windows 10 ?
Could you run `java -jar jansi-2.1.0.jar` and paste the output please in both cmd and PowerShell ?

**Comment by alexisjehan** [comment]
I confirm it works using ```java -jar jansi-2.1.0.jar```.

This code was working until 2.0.1:
```
public static void main(final String[] args) {
	final PrintStream output = AnsiConsole.out();
	output.println(Ansi.ansi().fgBrightRed().a("Hello world").reset());
}
```

I've had another look, and this is working with 2.1.0, adding a single line:
```
public static void main(final String[] args) {
	AnsiConsole.systemInstall();
	final PrintStream output = AnsiConsole.out();
	output.println(Ansi.ansi().fgBrightRed().a("Hello world").reset());
}
```

So since 2.1.0, ```AnsiConsole.systemInstall();``` appears to be required before using ```AnsiConsole.out();``` to get colors in both PowerShell and cmd. That was not the case in previous versions.

**Comment by gnodet** [comment]
Ah, yes, that's right.
If you want to restore the previous behavior, you can set the `jansi.eager` system property to `true`.
