### ISSUE TITLE
What to use in place of render?

### ISSUE THREAD

**Issue by boxleytw** [fusesource/jansi#184]
I've updated to latest Jansi from an older version.  Previously, I used code such as (Kotlin; Java is similar):
```
        println(ansi().render("""
@|bold f($n) = ${fib.char}|@
@|green F($n) = $fib|@
@|blue 1/F($n) = ${fib.multInv}|@
@|magenta det(F($n)) = ${fib.det}|@
@|yellow tr(F($n)) = ${fib.tr}|@
""".trim()))
```
I note the `render` method has gone away, and `format` does not seem to process the ANSI instructions for `@|...|@` bits in my string, and `AnsiRenderer` has gone away.

What is suggested to do in it's place?  I know about methods such as `bold`, but prefer being able to use string templates.

Thanks!

**Comment by gnodet** [comment]
I'll see if I can put the AnsiRenderer back.
