### ISSUE TITLE
publish JAnsi 2.3.0 and 2.3.1 tags

### ISSUE THREAD

**Issue by hboutemy** [fusesource/jansi#197]
@gnodet 
these releases are available on Central
but not in Git...

(what's the release process?)

**Comment by gnodet** [comment]
I pushed the commits / tags.  Not sure why this is not done automatically, I'm simply using the maven release plugin, but the automatic push must have been disabled.

**Comment by hboutemy** [comment]
do you use "origin" as remote name?
https://stackoverflow.com/questions/2730319/does-maven-release-plugin-push-tags-to-remote-git-repository
