### ISSUE TITLE
changelog.md does not explain what's new since 2.1.0

### ISSUE THREAD

**Issue by skyghis** [fusesource/jansi#200]
The `changelog.md` file does not explain what's new in `2.1.1`,  `2.2.0`, `2.3.0` and `2.3.1`.

Would you please update it, so we know what's changed ?

Thank you !

**Comment by gnodet** [comment]
Fixed with https://github.com/fusesource/jansi/commit/b7c7fbda5b19d5ad9f761e88bb06da8177cdc83e
