### ISSUE TITLE
Where can I find the JAR?

### ISSUE THREAD

**Issue by CATboardBETA** [fusesource/jansi#206]
In your provided usage, it shows just importing it. But when I do this, I get this error:

> Cannot resolve symbol 'fusesource'. 

I used `Alt+Enter => Find a Jar on the web`, but it found nothing. Where can I get a Jar for jansi?

**Comment by CATboardBETA** [comment]
For now, I am just downloading the source and putting it in another package in my code.

**Comment by renatoathaydes** [comment]
@CATboardBETA In the Java world, you get jars from a Maven repository.

Maven Central is the main repository:

https://search.maven.org/artifact/org.fusesource.jansi/jansi

You can manually download the jar from there, but you should really use either Maven or Gradle to do it for you.
