### ISSUE TITLE
Remove native methods not used by jansi

### ISSUE THREAD

**Issue by gnodet** [fusesource/jansi#208]
Jansi 2.3.0 introduced 2 native methods (`setenv` and `chdir`) which are used by https://github.com/mvndaemon/mvnd but not jansi, so they should be removed once https://github.com/mvndaemon/mvnd/issues/400 has been released.

**Comment by davsclaus** [comment]
@gnodet has that mvnd been released? If so then this ticket can be implemented

**Comment by gnodet** [comment]
Yes, definitely, I'll get rid of those two methods.
