### ISSUE TITLE
HtmlAnsiOutputStream removed from latest Jansi?

### ISSUE THREAD

**Issue by Osiris-Team** [fusesource/jansi#210]
Is it ever coming back, or should I create a new one by myself?

**Comment by gnodet** [comment]
There's no plan to bring it back at the moment, I don't think it's used enough.

**Comment by Osiris-Team** [comment]
@gnodet Im planning to write something for converting ansi to html.
Is there a way you would recommend how to tackle that?

**Comment by Osiris-Team** [comment]
@gnodet I was thinking of something like this:
```java
public class UtilsAnsiHtml {

    public String convertAnsiToHtml(Ansi ansi) throws IOException {
        StringBuilder builder = new StringBuilder();
        builder.append("<ansi>");
        String ansiString = ansi.toString();
        for (int i = 0; i < ansiString.length(); i++) {
            int currentCodePoint = ansiString.codePointAt(i);
            // TODO parse ansi
        }
        builder.append("</ansi>");
        return builder.toString();
    }

}
```

**Comment by gnodet** [comment]
@Osiris-Team I guess you should be able to adapt the `HtmlAnsiOutputStream` (https://github.com/fusesource/jansi/blob/jansi-1.x/jansi/src/main/java/org/fusesource/jansi/HtmlAnsiOutputStream.java) to the recent `AnsiOutputStream` from 2.x.

**Comment by Osiris-Team** [comment]
> @Osiris-Team I guess you should be able to adapt the `HtmlAnsiOutputStream` (https://github.com/fusesource/jansi/blob/jansi-1.x/jansi/src/main/java/org/fusesource/jansi/HtmlAnsiOutputStream.java) to the recent `AnsiOutputStream` from 2.x.

Yeah guess that should be easier haha

**Comment by Osiris-Team** [comment]
@gnodet What is the difference between this:
https://github.com/fusesource/jansi/blob/b7c7fbda5b19d5ad9f761e88bb06da8177cdc83e/src/main/java/org/fusesource/jansi/io/AnsiOutputStream.java#L88
and this:
https://github.com/fusesource/jansi/blob/b7c7fbda5b19d5ad9f761e88bb06da8177cdc83e/src/main/java/org/fusesource/jansi/io/AnsiOutputStream.java#L78
in AnsiOutputStream?

**Comment by Osiris-Team** [comment]
@gnodet https://github.com/fusesource/jansi/pull/212

**Comment by guusdk** [comment]
For the record - we were using HtmlAnsiOutputStream. Sad to see it go.

**Comment by Osiris-Team** [comment]
@guusdk i think support was added back in the latest version, at least there seems to be a merged PR for this.
Oh nevermind its a fork or another project: https://github.com/almond-sh/almond/pull/993
