### ISSUE TITLE
Allow interception of AnsiConsole's output

### ISSUE THREAD

**Issue by NilsRenaud** [fusesource/jansi#228]
This commit : https://github.com/fusesource/jansi/commit/57aa84d4120395922458f61f20e741198f051087
Has replaced `System.out` and `System.err` by `FileDescriptor.out` and `FileDescriptor.err`.

Although this seems related to Windows support, it is now impossible to test AnsiConsole when integrated in a project. This is why [Logback](http://logback.qos.ch/) project is [stuck in version 1.18](https://jira.qos.ch/browse/LOGBACK-1567) of JANSI.

As an example, here is a PR trying to upgrade JANSI version in logback : https://github.com/qos-ch/logback/pull/542/files

A possible solution could be to specify the `PrintStream` to use to AnsiConsole, or to use `System.out`/`System.err` back instead of `FileDescriptor`'s one.

**Comment by NilsRenaud** [comment]
@gnodet could you please explain the choice of using `FileDescriptor.out/err` instead of `System.out/err` ? 
Is it possible to come back to `System.out/err` ?

Thanks in advance !

**Comment by gnodet** [comment]
It's not really doable.  However, your test can be fixed with the following: https://github.com/gnodet/logback/commit/e60cd353b834f7e656345ad403f0cfed128e2863
