### ISSUE TITLE
Fix license name

### ISSUE THREAD

**Issue by michael-o** [fusesource/jansi#229]
The license name in the POM is wrong. It must read: Apache License, Version 2.0

See: https://github.com/apache/maven-apache-parent/blob/e3a75f29af4e8ab443ee4f2ee702c766a2f017f2/pom.xml#L45-L49

**Comment by gnodet** [comment]
I suppose you meant the following ?
```
      <name>The Apache Software License, Version 2.0</name>
```

**Comment by michael-o** [comment]
> I suppose you meant the following ?
> 
> ```
>       <name>The Apache Software License, Version 2.0</name>
> ```

Yes, that snippet is wrong.

**Comment by JakeWharton** [comment]
Per https://maven.apache.org/pom.html#Licenses the use of a SPDX identifier is now recommended so given https://spdx.org/licenses/Apache-2.0.html it should actually be "Apache-2.0".

**Comment by michael-o** [comment]
> Per https://maven.apache.org/pom.html#Licenses the use of a SPDX identifier is now recommended so given https://spdx.org/licenses/Apache-2.0.html it should actually be "Apache-2.0".

This maybe true, but MPIR's dependency report aggregates by name alomst every one is using the canonical name, not the SPDX id.

**Comment by JakeWharton** [comment]
It's not clear why we should honor some random tool's behavior over the canonical recommendation from the specification for the file in which this data exists.

Perhaps recommended to that tool that they should normalize the data toward the SPDX identifiers rather than naive name-based grouping.

**Comment by gnodet** [comment]
Ideally, the MPIR's dependency report would read https://github.com/spdx/license-list-data/blob/master/json/licenses.json and allows aggregating the full name with the short identifiers.

**Comment by michael-o** [comment]
> Ideally, the MPIR's dependency report would read https://github.com/spdx/license-list-data/blob/master/json/licenses.json and allows aggregating the full name with the short identifiers.

True, didn't know about this one. Please raise a JIRA issue for this. 
Surprisingly, [this](https://github.com/spdx/license-list-data/blob/master/json/licenses.json#L2299) does not match the name in the original license.

**Comment by gnodet** [comment]
Fixed with https://github.com/fusesource/jansi/commit/00e15cb1fab9117790580a412f7d54f2c08d2f11 and https://issues.apache.org/jira/projects/MPIR/issues/MPIR-407 was raised.
