### ISSUE TITLE
Investigate using FFM API

### ISSUE THREAD

**Issue by gnodet** [fusesource/jansi#230]

**Comment by gnodet** [comment]
https://openjdk.java.net/jeps/419

**Comment by axelfontaine** [comment]
+1

This would allow for jansi to eliminate JNI and fix countless issues in one go such as:
- #244 
- #245
- #246
- #241 
- #238
- #232

**Comment by gnodet** [comment]
Replaced with https://openjdk.org/jeps/434, still in preview...

Also see https://github.com/jline/jline3/pull/826

**Comment by Glavo** [comment]
The FFM API will end preview and be officially released in Java 22.
