### ISSUE TITLE
Is it possible to parse ansi text to get text and its attributes using Jansi?

### ISSUE THREAD

**Issue by PashaTurok** [fusesource/jansi#234]
For example I have the following string

`2022-03-14 02:32:24.130 [main] ESC[33;1m[WARN]ESC[m org.eclipse.aether.internal.impl.WarnChecksumPolicy `

Could anyone say if it is possible to parse this piece `ESC[33;1m[WARN]ESC[m ` to get color, brightness attribute and text (WARN) using Jansi?

**Comment by PavelKastornyy** [comment]
I wrote a [library](https://github.com/PavelKastornyy/ansi4j) that parses ANSI control functions. It supports all types of functions.
