### ISSUE TITLE
library.jansi.path not being used?

### ISSUE THREAD

**Issue by bdw429s** [fusesource/jansi#235]
Please see this issue https://github.com/jline/jline3/issues/778 for an error while using JLine.  The tool in question sets `library.jansi.path` yet it would appear the native library is being loaded from `/tmp`.  Is this system property still in use.

**Comment by gnodet** [comment]
I may have misleaded you, or maybe it has changed in between, not sure.
Anyway, the `library.jansi.path` is currently used as a directory where to load pre-extracted libraries from.  
If the native libraries are extracted from the jar, the [temporary dir](https://github.com/fusesource/jansi/blob/2cf446182c823a4c110411b765a1f0367eb8a913/src/main/java/org/fusesource/jansi/internal/JansiLoader.java#L80) will be used, using `jansi.tmpdir` or `java.io.tmpdir` if it is not defined.

**Comment by bdw429s** [comment]
@gnodet Thanks for the clarification.  I am already using `jna.tmpdir`, but I will add `jansi.tmpdir` as well.
