### ISSUE TITLE
Box drawing characters don't print correctly after AnsiConsole.systemInstall() in cmd.exe

### ISSUE THREAD

**Issue by codemonstur** [fusesource/jansi#247]
I want to print some box drawing characters to the screen. Here is my code:

    public static void main(final String... args) {
        AnsiConsole.systemInstall();
        System.out.println("\u2514\u2500");
    }

However this prints:

    C:\Projects\public\test>java -jar target/test.jar
    ÔööÔöÇ

If I remove the `AnsiConsole.systemInstall()` I get this:

    C:\Projects\public\test>java -jar target/test.jar
    └─

On linux everything is fine. This only breaks on windows (tested with cmd.exe and Windows Home 11).
I do want to continue using AnsiConsole because I want to print colors. And that part works great. I don't want to have to choose between colors or fancy drawing.

**Comment by codemonstur** [comment]
Hey @gnodet, I already did. See my comment here: https://github.com/fusesource/jansi/issues/227

**Comment by gnodet** [comment]
@codemonstur I've reproduced the issue when running on JDK 21.  Could you double check that it works for you with JDK 11 ? I'll investigate and try to find a fix in the mean time...
