### ISSUE TITLE
isatty test on windows 8.1 64bit

### ISSUE THREAD

**Issue by craigryan** [fusesource/jansi#34]
Firstly, your Project Home link (http://jansi.fusesource.org/) won't open, is this server down or gone?

I rely on both WindowsAnsiOutputStream and the simple isatty(fileno) test. I'm seeing the following behaviour when testing in three consoles - cmd.exe, cygwin term (TERM=xterm) and emacs shell (TERM=emacs) all on Win8.1. The '???' results are not expected. Jansi seems to only work with a native terminal when on Windows, the docs don't seem to suggest that though.
## 1. first test: testing isatty on its own

The output is debug, the program does a simple isatty test

d:/ runfoo 
TTY returns: 0, STDOUT_FILENO: 1  (output in cygwin term and emacs shell) **???**
TTY returns: 64, STDOUT_FILENO: 1 (output on Win cmd.exe, as expected)

d:/ runfoo | cat      (pipe to another command)
TTY returns: 0, STDOUT_FILENO: 1  (output in cygwin term and emacs shell as expected)
TTY returns: 0, STDOUT_FILENO: 1 (output on Win cmd.exe, as expected)
## 2. Test WindowsAnsiOutputStream (no isatty checks)

Program creates the stream and outputs data containing some ansi highligting codes. 

d:/ runbah

.. throws an exception when creating the stream instance (cygwin and emacs shell) **???**
.. works as expected (cmd.exe, output is highlighted correctly)

d:/ runbah | cat

.. throws an exception (all three) **???**

I haven't tested Linux at all yet for the isatty checks. 

Can anyone explain this? 

For the first test, is it not possible for jansi to work consistently in all these cases so that I can check for a TTY regardless of which console I'm in?

For the second test, it makes sense for jansi to throw an exception for real JNI/JNA issues, but for redirected output it doesn't make sense. Would it work to have WindowsAnsiOutputStream do its own isatty check and, if false, revert to AnsiOutputStream behaviour?

**Comment by MagicDroidX** [comment]
:(
It doesn't work properly on me.
I think it's my mistake.
I use Jansi in this way:
AnsiConsole.systemInstall();
than i try to output some messages with Ansi escape string.
My cmd.exe doesn't show the color of my messages (nor the Ansi escape string).
What's wrong? Plz help me ,Thx.

**Comment by davsclaus** [comment]
Closing old tickets.
