### ISSUE TITLE
website mentioned in readme is unavailable

### ISSUE THREAD

**Issue by jodygarnett** [fusesource/jansi#37]
README links to http://jansi.fusesource.org/ - which does not respond.

**Comment by akuji1993** [comment]
Issue is still existent, can't access the site.

**Comment by HwapX** [comment]
Here too

**Comment by tag** [comment]
Continues to be an issue.

**Comment by PascalSchumacher** [comment]
readme now links to http://fusesource.github.io/jansi/ so this issue can be closed
