### ISSUE TITLE
license migration 

### ISSUE THREAD

**Issue by jodygarnett** [fusesource/jansi#38]
Looking at the [license.txt](https://github.com/fusesource/jansi/blob/master/license.txt) history the project changed from:
- GNU Affero General Public License, Jul 6, 2009
- Apache License Version 2.0 - Jul 6, 2009

Both of these are on the same day? Was it a case of uploading with the wrong initial license and then quickly correcting the mistake?

I am trying to confirm @chirino was an employee (of the copyright owner) at the time and had the correct permission to release this under the Apache License. It is a little complicated as GitHub shows @chirino joining on Jul 9th several days after the above file history had been changed!

**Comment by jodygarnett** [comment]
Sorry to be a bother on this stuff, we are doing an IP review as our project joins a software foundation (and we just got JLine rejected over exactly this kind of thing). We would like to double check before migrating our code to use jansi ...

**Comment by chirino** [comment]
Yes. It was just a correction.

**Comment by jodygarnett** [comment]
Thanks!
