### ISSUE TITLE
Color blue is not readable on Windows. 

### ISSUE THREAD

**Issue by tomas-langer** [fusesource/jansi#42]
It would be nice to use a different color for ANSI blue on Windows. 

For example in npm and related tools (javascript tools) they use a light version of blue
![full_comparison](https://cloud.githubusercontent.com/assets/13766491/11930578/f545e192-a7e4-11e5-86a2-b6257ccdf2be.PNG)
In the picture above: top area is printed using Jansi, bottom area original javascript tool.

**Comment by janschaefer** [comment]
This should do the trick: `Ansi.ansi().bgBright( Color.BLUE )`
