### ISSUE TITLE
Add support for grey color

### ISSUE THREAD

**Issue by tomas-langer** [fusesource/jansi#43]
There is not grey color support in JANSI. Standard ANSI supports it (begin escape code 90). It works fine on linuxes and other ANSI color enabled views (AnsiColor for Jenkins, IntelliJ idea output, javasript tools).

Example - top area printed through JANSI, bottom from javascript grunt tool. I would like to achieve the same...

![full_comparison](https://cloud.githubusercontent.com/assets/13766491/11930630/8190f664-a7e5-11e5-9918-28bc14238537.PNG)

If I send the correct ansi code, JANSI prints it as black...

**Comment by janschaefer** [comment]
This is actually supported. Just do: `Ansi.ansi().fgBright( Color.BLACK )`

**Comment by tomas-langer** [comment]
Hi, using version jansi-native:1.5 and this doesn't work. Do I need to switch to snapshot versions? Seems the method FillConsoleOutputAttribute is not there yet...

**Comment by garydgregory** [comment]
Why not add a Color.GREY then?

**Comment by gnodet** [comment]
Because there's no value for GREY.  It's either fgBright(Color.BLACK) or bgBright(Color.BLACK), depending if you use it as the text or background.
