### ISSUE TITLE
Can we cut a new release?

### ISSUE THREAD

**Issue by jdbernard** [fusesource/jansi#44]
It looks like the last release was 1.11 back in 2013. Are there plans to release 1.12 at some point? If so, can that point be soon? :smile:

**Comment by garydgregory** [comment]
+1

Gary

**Comment by PascalSchumacher** [comment]
issue can be closed as 1.12 was release a while ago: https://github.com/fusesource/jansi/commit/32f99fe8b7162792288bd552508835f4dc61895d

**Comment by jdbernard** [comment]
Awesome, thanks!
