### ISSUE TITLE
Statement about "Windows XP Users" is incorrect

### ISSUE THREAD

**Issue by michael-o** [fusesource/jansi#53]
The statement says that Win XP users need to add the redist library. This is not true. The MS documentation says:

>  Windows 2000 Service Pack 4, Windows 7, Windows Server 2003, Windows Server 2008, Windows Server 2008 R2, Windows Vista, Windows XP

So, I assume it applies to several Windows flavors, not only Win XP.

Please update the title and the statement.

**Comment by davsclaus** [comment]
Remove the doc about win xp
