### ISSUE TITLE
Provide FreeBSD native support by default

### ISSUE THREAD

**Issue by michael-o** [fusesource/jansi#56]
This depens on fusesource/jansi-native#5 and would simply require to add two dependencies. As mentioned in the issue, I am willing to provide these. #55 depends on.

**Comment by gnodet** [comment]
I've deployed a snapshot will FreeBSD support at
  https://oss.sonatype.org/content/repositories/snapshots

**Comment by michael-o** [comment]
Will test tomorrow, can you tell me what you have used to build? Which FreeBSD version and Compiler?

**Comment by gnodet** [comment]
FreeBSD 11, gcc 4.8.5

**Comment by michael-o** [comment]
Just tested on FreeBSD 10.3-RELEASE, 32 bit. It does work. I have already found a bug in Jansi, I guess.
