### ISSUE TITLE
changelog.md does not explain what's new in 1.12 and 1.13

### ISSUE THREAD

**Issue by garydgregory** [fusesource/jansi#57]
The changelog.md file does not explain what's new in 1.12 and 1.13. 

Would you please update it so we know what's what?

Thank you!

**Comment by kmort89** [comment]
Bump!
This needs to be addressed and the issue is half a year old already.

**Comment by paulk-asert** [comment]
Ditto for 1.14 and 1.15 or is this information somewhere else now?

**Comment by paulk-asert** [comment]
Thanks
