### ISSUE TITLE
Add complex examples

### ISSUE THREAD

**Issue by albfan** [fusesource/jansi#62]
Would be cool to see the code behind the logo (seems that it is rendered from a java execution, isn't it?)

![jansi logo](http://i.stack.imgur.com/lENdw.png)

**Comment by gnodet** [comment]
The example simply dumps the content of the following file:
 https://github.com/fusesource/jansi/blob/master/jansi/src/test/resources/jansi.ans

**Comment by albfan** [comment]
Thanks
