### ISSUE TITLE
Windows 10 supports ANSI natively

### ISSUE THREAD

**Issue by cowwoc** [fusesource/jansi#63]
Please update the library taking http://superuser.com/a/1105718/57662 into consideration.

**Comment by hboutemy** [comment]
Should we remove the JAnsi System.out tweaking for any Windows 10 version?
Or should we try to check for a minimal build?
Any PR?

**Comment by gnodet** [comment]
It seems that this support has been removed from Windows 10:
  https://github.com/symfony/symfony/issues/19520

**Comment by cowwoc** [comment]
@gnodet It's not removed but rather disabled by default. See https://github.com/Microsoft/BashOnWindows/issues/1173

All this is to say that you need native code to activate support.

**Comment by gnodet** [comment]
So it seems what would be needed is to call `setConsoleMode(ENABLE_VIRTUAL_TERMINAL_PROCESSING)` when Windows 10 is detected.
Additionally, we'd need to detect windows 10 ;-)

I don't really see that as a priority though, given jansi aims to provide the same thing on all windows versions, and this is also working for Windows 10.

**Comment by dmlloyd** [comment]
JDK 11 does seem to have a `jline` impl hidden inside of it... with a JNA bridge to `SetConsoleMode`...

https://github.com/unofficial-openjdk/openjdk/blob/jdk/jdk/src/jdk.internal.le/windows/classes/jdk/internal/org/jline/terminal/impl/jna/win/Kernel32.java#L217-L222
