### ISSUE TITLE
System.out.print isn't working after calling AnsiConsole.systemInstall();

### ISSUE THREAD

**Issue by ghost** [fusesource/jansi#91]
Title

**Comment by gnodet** [comment]
What do you mean it does not work ? Please be more specific.

**Comment by LavaGhost** [comment]
if you put
`
AnsiConsole.systemInstall();
System.out.print("Test");
`
nothing will print, however.
`
AnsiConsole.systemInstall();
System.out.println("Test");
`
works normally.

**Comment by sebialex** [comment]
@LavaGhost I'm also having this issue.

**Comment by gnodet** [comment]
Have you tried using ```System.out.print("Test"); System.out.flush();` ?

**Comment by sebialex** [comment]
Thanks, I'll try it out.

**Comment by MegaCookie** [comment]
I had the same issue. For me `System.out.print` does work on Windows but not on Bash-like terminals, there I had to use `System.out.flush();` as @gnodet suggested.

**Comment by hboutemy** [comment]
it should be fixed by #95, which fixes encoding issues but also removes the flush requirement
if you can test latest SNAPSHOT, please do and confirm

**Comment by MegaCookie** [comment]
@hboutemy yes it works. I built the project with Maven and using the new jansi-1.17-SNAPSHOT.jar

**Comment by MegaCookie** [comment]
I noticed in the new snapshot, if the command line is forced to close (CTRL+C), there can be an issue that the custom color is displayed everywhere, even after closing.   
Re-running of the programming doesn't solve it. (Maybe I should make another issue)

**Comment by hboutemy** [comment]
yes, this is another issue
and on this one, I don't see how to detect and reset...

**Comment by slachiewicz** [comment]
@MegaCookie  please verify with latest SNAPSHOT, - from my tests problem with Ctrl-C should be fixed now

**Comment by 936707967xxy** [comment]
你好，怎么添加logo？

**Comment by gnodet** [comment]
The streams are in auto flush mode in 2.x, but a simple `System.out.print("foo")` does not ensure the string is written.  the auto flush only kicks in when a newline is written, so an explicit call to `flush()` is required.
