### ISSUE TITLE
Non-ascii chars incorrectly handled on Windows 7 with IBM JDK

### ISSUE THREAD

**Issue by andham** [fusesource/jansi#93]
Non-ascii chars (å, ä, ö for example) are displayed as question mark ('?') on Windows 7 when using IBM JDK 1.8. With Oracle JDK 1.8 it works.
This was originally reported on the Apache Maven project: https://issues.apache.org/jira/browse/MNG-6205
IBM JDK can be downloaded here: https://www.ibm.com/developerworks/java/jdk/

One way to test is to add the following line to Main.java in the example module:
    System.out.println("System.out: " + "åäö");

**Comment by hboutemy** [comment]
Anders, can you check this PR please? It should fix the issue since any encoding management is removed by extending PrintStream (old OutputStream based code is still here just for compatibility)

**Comment by andham** [comment]
I've tested #95 with IBM SDK 7.1 and IBM SDK 8 in Maven 3.5.0 on Windows 7 and it seems to work with that fix. :+1:

**Comment by hboutemy** [comment]
great, now I'll try to get Jansi team attention to merge :)

**Comment by hboutemy** [comment]
#95 merged, closing the issue
