### ISSUE TITLE
API changes in Jansi

### ISSUE THREAD

**Issue by lvc** [fusesource/jansi#96]
Hi,

I'd like to share report on API changes and backward binary compatibility for the Jansi library: https://abi-laboratory.pro/java/tracker/timeline/jansi/

The report is generated by the https://github.com/lvc/japi-tracker tool according to the article https://wiki.eclipse.org/Evolving_Java-based_APIs_2 for jars at http://central.maven.org/maven2/org/fusesource/jansi/jansi/.

The report is automatically updated 3 times a week. Hope it will be helpful for users and maintainers of the library.

Thank you.

![jansi-2](https://user-images.githubusercontent.com/1517837/31849938-767f6174-b653-11e7-86ee-1003bcbe5673.png)

![jansi-1](https://user-images.githubusercontent.com/1517837/31849939-76b8e796-b653-11e7-988f-ea4107b6976f.png)

**Comment by gnodet** [comment]
Thx !
