### ISSUE TITLE
saveCursorPosition()&restoreCursorPosition() not working on Ubuntu

### ISSUE THREAD

**Issue by Franky0107** [fusesource/jansi#97]
I am working on a cross platform project. It aims to display the progress when executing some specific task in terminal, and when new data coming in, it should overwrite previous progress. 
When testing on Ubuntu, saveCursorPosition()&restoreCursorPosition() are totally not working, and all output comes out in sequence.  While on my local machine, a win 10, it works. (Though not perfect, always one line below the desired position, can be fixed anyway :) )

**Comment by slachiewicz** [comment]
Do you have sample code that we can reproduce issue?

**Comment by gnodet** [comment]
See https://github.com/fusesource/jansi/issues/195, the problem does not seem to come from Jansi, but rather from the terminals that do not support those commands.
