### ISSUE TITLE
Why jansi-*.dll is extracted in %TMP% ? How can I avoid that ?

### ISSUE THREAD

**Issue by glhez** [fusesource/jansi#98]
I am using jansi-1.16 in a small project which is an application that I invoke every now and then.
At a result, here is what jansi does: it extract a lot of dll into my %TMP% folder as shown below.

=> I understand that it is required, but could it not use some more stable path, such as `${user.home}/.jansi/jansi-<version>.dll` ?

![image](https://user-images.githubusercontent.com/10855953/32132960-1f968a1a-bbce-11e7-8853-078d4828dcf0.png)

**Comment by michael-o** [comment]
That'really ugly...

**Comment by hboutemy** [comment]
looks like Windows is not able to do dll cleanup on exit...
what you can do is set {{-Dlibrary.jansi.path=}} to point to the location where native libs are extracted

**Comment by glhez** [comment]
As I understood, that will force JANSI to use a folder. I see that maven is already using it and I'll check it.

But could you not use a predictive filename or directory when extracting into %TMP%:

- For directory, you could use `%USERPROFILE%\.jansi` or `%USERPROFILE%\AppData\Local\Jansi` (better) ?
- For file, you could use jansi-<version> or add a SHA1 in the filename to avoid naming collision ?

The first would add more junk to the `%USERPROFILE%` but still provide a unique directory containing jansi DLLs per version, the second would allow reusing a file found in %TMP%.

**Comment by xiezhaokun** [comment]
https://github.com/fusesource/hawtjni/commit/bd514b71878415e7091b914420a291310de3ec30

**Comment by michael-o** [comment]
Put the file into `%PATH%` and the extraction won't happen.

**Comment by gnodet** [comment]
Jansi 2.x does not use HawtJNI anymore, so this may still be a problem in 2.x.
https://github.com/fusesource/hawtjni/commit/bd514b71878415e7091b914420a291310de3ec30 could be ported to the new `JansiLoader` maybe.

**Comment by gnodet** [comment]
The library has to be extracted before being loaded.
Jansi 2.x now has a [`cleanup()`](https://github.com/fusesource/jansi/blob/090132d8160e50ef0c9d4b85990b32744f14e439/src/main/java/org/fusesource/jansi/internal/JansiLoader.java#L84) method which is called and that remove previously extracted libraries, so the number of files should not go beyond the number of concurrent use of the libraries for a given version.
